//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fcog.Controls.Wpf.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fcog.Controls.Wpf.Localization.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string AddSing {
            get {
                return ResourceManager.GetString("AddSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author.
        /// </summary>
        public static string AuthorSign {
            get {
                return ResourceManager.GetString("AuthorSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cells.
        /// </summary>
        public static string CellsSign {
            get {
                return ResourceManager.GetString("CellsSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of Creation.
        /// </summary>
        public static string CreationDateTimeSign {
            get {
                return ResourceManager.GetString("CreationDateTimeSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string DescriptionSign {
            get {
                return ResourceManager.GetString("DescriptionSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUID.
        /// </summary>
        public static string GuidSign {
            get {
                return ResourceManager.GetString("GuidSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index.
        /// </summary>
        public static string IndexSing {
            get {
                return ResourceManager.GetString("IndexSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Label.
        /// </summary>
        public static string LabelSing {
            get {
                return ResourceManager.GetString("LabelSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LanguageSing {
            get {
                return ResourceManager.GetString("LanguageSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string NameSign {
            get {
                return ResourceManager.GetString("NameSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Cell.
        /// </summary>
        public static string NewCellSign {
            get {
                return ResourceManager.GetString("NewCellSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Question.
        /// </summary>
        public static string NewQuestionSign {
            get {
                return ResourceManager.GetString("NewQuestionSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Questionnaire Properties.
        /// </summary>
        public static string QPropertiesSign {
            get {
                return ResourceManager.GetString("QPropertiesSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question Type.
        /// </summary>
        public static string QuestionTypeSign {
            get {
                return ResourceManager.GetString("QuestionTypeSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string RemoveSing {
            get {
                return ResourceManager.GetString("RemoveSing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string StatisticsSign {
            get {
                return ResourceManager.GetString("StatisticsSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test dataset.
        /// </summary>
        public static string TestDataSetSign {
            get {
                return ResourceManager.GetString("TestDataSetSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total:.
        /// </summary>
        public static string TotalSign {
            get {
                return ResourceManager.GetString("TotalSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train dataset.
        /// </summary>
        public static string TrainDataSetSign {
            get {
                return ResourceManager.GetString("TrainDataSetSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string VersionSign {
            get {
                return ResourceManager.GetString("VersionSign", resourceCulture);
            }
        }
    }
}
